from . import start, registration, callback, menu, cancel, date, delete, info, exit, overdue, announcements, marks, detail_marks, invitechat, connect, disconnect, moderadd, moderdel, moders, dz, dnevnik, chatrasp, chatdz, chatmarks, chat_detail_marks, custom_dz, calls

bps = [start.bp,
		registration.bp,
		callback.bp,
		menu.bp,
		cancel.bp,
		date.bp,
		delete.bp,
		info.bp,
		exit.bp,
		overdue.bp,
		announcements.bp,
		marks.bp,
		detail_marks.bp,
		invitechat.bp,
		connect.bp,
		disconnect.bp,
		moderadd.bp,
		moderdel.bp,
		moders.bp,
		dz.bp,
		dnevnik.bp,
		chatrasp.bp,
		chatdz.bp,
		chatmarks.bp,
		chat_detail_marks.bp,
		custom_dz.bp,
		calls.bp]